#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

class Novice
{
    protected $commandPaths = [
        'App\Lib\Slime\Console\Commands\\',
        'App\Console\\'
    ];

    function __construct($args)
    {
        $this->args = $args;
    }

    function help()
    {
        echo "usage: php " . $this->args[0] . " <command> [<args>]\n";
        exit(1);
    }

    function exec()
    {
        if (count($this->args) <= 1) {
            $this->help();
        }

        $args = array_slice($this->args, 2);
        $commandClass = $this->getCommandClass($this->args[1]);

        if (empty($commandClass)) {
            echo "Command not found\n";
            exit(1);
        }

        $command = $this->createCommandClass($commandClass, $args);
        $command->run();
    }

    private function getCommandClass($commandName)
    {
        foreach ($this->commandPaths as $commandPath) {
            $commandFullName = $commandPath . ucfirst($commandName) . 'Command';
            if (class_exists($commandFullName)) {
                return $commandFullName;
            }
        }

        return false;
    }

    private function createCommandClass($commandClass, $args)
    {
        return new $commandClass($args);
    }
}

$novice = new Novice($argv);
$novice->exec();